import type { Metadata } from 'next';
import Legal from '@/components/Legal/Legal';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The terms that govern your use of the TARDIS website and web app — visualization accuracy, acceptable use, intellectual property, and liability.',
  alternates: { canonical: 'https://www.tardis-ai.com/terms' },
};

export default function TermsPage() {
  return (
    <Legal title="Terms of Service" updated="June 4, 2026">
      <p>
        These Terms of Service govern your use of the TARDIS website at tardis-ai.com and web app
        at app.tardis-ai.com, operated by TARDIS (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or
        &ldquo;our&rdquo;). By using the service, you agree to these terms. If you do not agree,
        do not use the service.
      </p>

      <h2>What TARDIS does</h2>
      <p>
        TARDIS is an AI-powered furniture visualization tool. You submit a furniture product URL
        or image, and we generate an interactive 3D model you can view in augmented reality. The
        service is provided as-is during our early access period.
      </p>

      <h2>Visualization accuracy</h2>
      <p>
        3D models and AR visualizations generated by TARDIS are estimates based on AI processing.
        They are intended to give you a general sense of how a piece of furniture might look and
        fit in your space.
      </p>
      <p>
        <strong>
          Do not rely on TARDIS renderings as precise representations of product dimensions,
          color, material, or spatial fit. Always verify actual product specifications and
          measurements directly with the retailer before making a purchase.
        </strong>
      </p>
      <p>We disclaim any liability for purchase decisions made in reliance on TARDIS visualizations.</p>

      <h2>No retailer affiliation</h2>
      <p>
        TARDIS is an independent service. We are not affiliated with, endorsed by, or partnered
        with IKEA, Wayfair, CB2, West Elm, or any other furniture retailer or brand. Product
        names, images, and trademarks belong to their respective owners.
      </p>
      <p>
        When you paste a retailer URL into TARDIS, we process publicly available product
        information to generate a model. We do not guarantee compatibility with any particular
        retailer&apos;s website or product catalog.
      </p>

      <h2>Acceptable use</h2>
      <p>You may use TARDIS for personal, non-commercial visualization purposes. You agree not to:</p>
      <ul>
        <li>Submit content you do not have the right to share, including images you do not own or have licensed</li>
        <li>Use the service to infringe any intellectual property rights</li>
        <li>Attempt to reverse engineer, scrape, or extract data from the TARDIS platform</li>
        <li>Use the service in any way that violates applicable law or regulation</li>
        <li>Submit content that is harmful, deceptive, or unlawful</li>
      </ul>
      <p>We reserve the right to suspend or terminate access for violations of these terms.</p>

      <h2>Intellectual property</h2>
      <p>
        <strong>Your content.</strong> You retain ownership of any images you upload. By
        submitting content to TARDIS, you grant us a limited, non-exclusive license to process and
        use that content solely to provide the service to you. We do not claim ownership of your
        uploads.
      </p>
      <p>
        <strong>Our service.</strong> The TARDIS platform, software, 3D generation pipeline,
        branding, and generated output (excluding your original input) are owned by or licensed to
        TARDIS. You may not copy, reproduce, or redistribute our software or generated assets
        outside of normal personal use of the service.
      </p>

      <h2>No warranties</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
        warranties of any kind, express or implied. We do not warrant that the service will be
        error-free, uninterrupted, or suitable for any particular purpose. Visualization outputs
        do not constitute professional interior design advice.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by applicable law, TARDIS and its founders will not be
        liable for any indirect, incidental, special, or consequential damages arising out of your
        use of the service, including purchasing decisions, reliance on visualization accuracy, or
        service interruptions.
      </p>
      <p>
        Our total liability to you for any claim arising from use of the service will not exceed
        the greater of USD $50 or the amount you paid us in the 12 months preceding the claim
        (currently zero, as the service is free).
      </p>

      <h2>Termination</h2>
      <p>
        We may suspend or terminate your access to the service at any time, for any reason, with
        or without notice. You may stop using the service at any time. These terms survive
        termination to the extent their nature requires it.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of Poland, without regard to
        conflict-of-law rules. Disputes arising under these terms will be
        resolved in the courts of Poland.
      </p>

      <h2>Changes to terms</h2>
      <p>
        We may update these terms as the service evolves. Material changes will be posted on this
        page with an updated effective date. Continued use of the service after changes are posted
        means you accept the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms: <a href="mailto:founders@tardis-ai.com">founders@tardis-ai.com</a>
      </p>
    </Legal>
  );
}
